name: Release Helm Chart

on:
  push:
    tags:
      - "v*"

env:
  GO_VERSION: "1.22.4"
  IMAGE_NAME: ghcr.io/stianfro/renovate-test

jobs:
  kustomize:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up Ko
        uses: ko-build/setup-ko@v0.6

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.15.3
        id: install

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Set BUILD_VERSION for tag push
        id: set_build_version
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "BUILD_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "BUILD_VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Build image
        env:
          PACKAGE_NAME: github.com/stianfro/renovate-test
        run: |
          KO_DOCKER_REPO=${{ env.IMAGE_NAME }}
          DIGEST=$(ko build --bare -t $BUILD_VERSION | tee /dev/tty | grep -o 'sha256:[a-f0-9]\{64\}')
          echo "IMAGE_DIGEST=$DIGEST" >> $GITHUB_ENV

      - name: Update manifests
        run: |
          kustomize edit set image controller=${{ env.IMAGE_NAME }}:$BUILD_VERSION@$IMAGE_DIGEST
          cat kustomization.yaml
          kustomize build > chart/templates/manifest.yaml

      - name: Release chart
        run: |
          helm package chart/ --version $BUILD_VERSION --app-version $BUILD_VERSION
          helm push renovate-test-chart-$BUILD_VERSION.tgz oci://ghcr.io/stianfro